// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shelter.BuildingBlocks.Persistence;

#nullable disable

namespace Shelter.Migrations.Migrations
{
    [DbContext(typeof(ShelterDbContext))]
    partial class ShelterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("claim_type")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("claim_value")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.HasKey("Id")
                        .HasName("pk_user_claim");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claim_user_id");

                    b.ToTable("user_claim", "platform");

                    b.HasAnnotation("Shelter:AuditSubject", "UserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_key")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provider_display_name")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_login");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_login_user_id");

                    b.ToTable("user_login", "platform");

                    b.HasAnnotation("Shelter:AuditSubject", "UserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_token");

                    b.ToTable("user_token", "platform");

                    b.HasAnnotation("Shelter:AuditSubject", "UserId");
                });

            modelBuilder.Entity("Shelter.BuildingBlocks.Auditing.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_type");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.HasKey("Id")
                        .HasName("pk_audit_event");

                    b.HasIndex("TenantId", "SubjectId")
                        .HasDatabaseName("ix_audit_event_tenant_id_subject_id");

                    b.HasIndex("TenantId", "EntityType", "EntityId", "TimestampUtc")
                        .HasDatabaseName("ix_audit_event_tenant_id_entity_type_entity_id_timestamp_utc");

                    b.ToTable("audit_event", "audit");
                });

            modelBuilder.Entity("Shelter.BuildingBlocks.Auditing.PersonDataKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ShreddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shredded_at");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<byte[]>("WrappedKey")
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_key");

                    b.HasKey("Id")
                        .HasName("pk_person_data_key");

                    b.HasIndex("TenantId", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_person_data_key_tenant_id_subject_id");

                    b.ToTable("person_data_key", "audit");
                });

            modelBuilder.Entity("Shelter.Modules.Animals.Domain.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("BehaviourAlert")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("behaviour_alert")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<bool>("BirthDateEstimated")
                        .HasColumnType("boolean")
                        .HasColumnName("birth_date_estimated")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("breed")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Colour")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("colour")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid?>("CurrentIntakeId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_intake_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid?>("CurrentLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_location_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("CustodyStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("custody_status")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<DateTimeOffset?>("InCareSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("in_care_since")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("LastOutcomeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_outcome_code")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("LegalAlert")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("legal_alert")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Marks")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("marks")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("MedicalAlert")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("medical_alert")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("ReproductiveStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reproductive_status")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("search_text")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("SecondaryBreed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("secondary_breed")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sex")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("SpeciesCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("species_code")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.HasKey("Id")
                        .HasName("pk_animal");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_animal_tenant_id_id");

                    b.HasIndex("SearchText")
                        .HasDatabaseName("ix_animal_search_text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("TenantId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_animal_tenant_id_number");

                    b.HasIndex("TenantId", "SpeciesCode")
                        .HasDatabaseName("ix_animal_tenant_id_species_code");

                    b.HasIndex("TenantId", "CustodyStatus", "CurrentLocationId")
                        .HasDatabaseName("ix_animal_tenant_id_custody_status_current_location_id");

                    b.ToTable("animal", "animals", t =>
                        {
                            t.HasCheckConstraint("ck_animal_custody", "(custody_status = 'in_care') = (current_location_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_animal_number", "number > 0");
                        });
                });

            modelBuilder.Entity("Shelter.Modules.Animals.Domain.AnimalIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("normalized_value")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("value")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.HasKey("Id")
                        .HasName("pk_animal_identifier");

                    b.HasIndex("TenantId", "AnimalId")
                        .HasDatabaseName("ix_animal_identifier_tenant_id_animal_id");

                    b.HasIndex(new[] { "TenantId", "NormalizedValue" }, "ix_animal_identifier_tenant_id_normalized_value")
                        .HasDatabaseName("ix_animal_identifier_tenant_id_normalized_value");

                    b.HasIndex(new[] { "TenantId", "NormalizedValue" }, "ux_animal_identifier_active_microchip")
                        .IsUnique()
                        .HasDatabaseName("ux_animal_identifier_active_microchip")
                        .HasFilter("is_active AND type = 'microchip'");

                    b.ToTable("animal_identifier", "animals");
                });

            modelBuilder.Entity("Shelter.Modules.Animals.Domain.AnimalNumberCounter", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<int>("LastNumber")
                        .HasColumnType("integer")
                        .HasColumnName("last_number")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.HasKey("TenantId")
                        .HasName("pk_animal_number_counter");

                    b.ToTable("animal_number_counter", "animals");
                });

            modelBuilder.Entity("Shelter.Modules.Animals.Domain.Species", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Label", "Shelter.Modules.Animals.Domain.Species.Label#LocalizedText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_en")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_fr")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");
                        });

                    b.HasKey("Code")
                        .HasName("pk_species");

                    b.ToTable("species", "animals");
                });

            modelBuilder.Entity("Shelter.Modules.Animals.Domain.SpeciesOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Label", "Shelter.Modules.Animals.Domain.SpeciesOverride.Label#LocalizedText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_en")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_fr")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");
                        });

                    b.HasKey("Id")
                        .HasName("pk_species_override");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_species_override_tenant_id_code");

                    b.ToTable("species_override", "animals");
                });

            modelBuilder.Entity("Shelter.Modules.Animals.Domain.TimelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_module")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid?>("SourceRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_record_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.HasKey("Id")
                        .HasName("pk_timeline_event");

                    b.HasIndex("TenantId", "AnimalId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_timeline_event_tenant_id_animal_id_occurred_at_id");

                    b.ToTable("timeline_event", "animals");
                });

            modelBuilder.Entity("Shelter.Modules.Movements.Domain.IntakeReason", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("SacCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sac_category")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Label", "Shelter.Modules.Movements.Domain.IntakeReason.Label#LocalizedText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_en")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_fr")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");
                        });

                    b.HasKey("Code")
                        .HasName("pk_intake_reason");

                    b.ToTable("intake_reason", "movements");
                });

            modelBuilder.Entity("Shelter.Modules.Movements.Domain.IntakeReasonOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("SacCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sac_category")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Label", "Shelter.Modules.Movements.Domain.IntakeReasonOverride.Label#LocalizedText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_en")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_fr")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");
                        });

                    b.HasKey("Id")
                        .HasName("pk_intake_reason_override");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_intake_reason_override_tenant_id_code");

                    b.ToTable("intake_reason_override", "movements");
                });

            modelBuilder.Entity("Shelter.Modules.Movements.Domain.Movement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid?>("FromLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_location_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reason_code")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid?>("ToLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_location_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid?>("VoidsMovementId")
                        .HasColumnType("uuid")
                        .HasColumnName("voids_movement_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.HasKey("Id")
                        .HasName("pk_movement");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_movement_tenant_id_id");

                    b.HasIndex("TenantId", "VoidsMovementId")
                        .IsUnique()
                        .HasDatabaseName("ix_movement_tenant_id_voids_movement_id")
                        .HasFilter("voids_movement_id IS NOT NULL");

                    b.HasIndex("TenantId", "AnimalId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_movement_tenant_id_animal_id_occurred_at_id");

                    b.ToTable("movement", "movements", t =>
                        {
                            t.HasCheckConstraint("ck_movement_shape", "(type = 'intake' AND reason_code IS NOT NULL AND to_location_id IS NOT NULL AND from_location_id IS NULL AND voids_movement_id IS NULL)\nOR (type = 'relocation' AND reason_code IS NULL AND from_location_id IS NOT NULL AND to_location_id IS NOT NULL AND from_location_id <> to_location_id AND person_id IS NULL AND voids_movement_id IS NULL)\nOR (type = 'outcome' AND reason_code IS NOT NULL AND from_location_id IS NOT NULL AND to_location_id IS NULL AND voids_movement_id IS NULL)\nOR (type = 'void' AND reason_code IS NULL AND from_location_id IS NULL AND to_location_id IS NULL AND voids_movement_id IS NOT NULL AND notes IS NOT NULL)");

                            t.HasCheckConstraint("ck_movement_type", "type IN ('intake', 'relocation', 'outcome', 'void')");
                        });

                    b.HasAnnotation("Shelter:AuditSubject", "PersonId");
                });

            modelBuilder.Entity("Shelter.Modules.Movements.Domain.OutcomeType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("SacCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sac_category")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Label", "Shelter.Modules.Movements.Domain.OutcomeType.Label#LocalizedText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_en")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_fr")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");
                        });

                    b.HasKey("Code")
                        .HasName("pk_outcome_type");

                    b.ToTable("outcome_type", "movements");
                });

            modelBuilder.Entity("Shelter.Modules.Movements.Domain.OutcomeTypeOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("SacCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sac_category")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Label", "Shelter.Modules.Movements.Domain.OutcomeTypeOverride.Label#LocalizedText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_en")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_fr")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");
                        });

                    b.HasKey("Id")
                        .HasName("pk_outcome_type_override");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_outcome_type_override_tenant_id_code");

                    b.ToTable("outcome_type_override", "movements");
                });

            modelBuilder.Entity("Shelter.Modules.Operations.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("KindCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kind_code")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.HasKey("Id")
                        .HasName("pk_location");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_location_tenant_id_id");

                    b.HasIndex("TenantId", "ParentId")
                        .HasDatabaseName("ix_location_tenant_id_parent_id");

                    b.HasIndex("TenantId", "ParentId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_location_tenant_id_parent_id_normalized_name")
                        .HasFilter("NOT is_archived");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TenantId", "ParentId", "NormalizedName"), false);

                    b.ToTable("location", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_location_capacity", "capacity IS NULL OR capacity BETWEEN 0 AND 10000");
                        });
                });

            modelBuilder.Entity("Shelter.Modules.Operations.Domain.LocationKind", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<bool>("HoldsAnimals")
                        .HasColumnType("boolean")
                        .HasColumnName("holds_animals")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Label", "Shelter.Modules.Operations.Domain.LocationKind.Label#LocalizedText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_en")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_fr")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");
                        });

                    b.HasKey("Code")
                        .HasName("pk_location_kind");

                    b.ToTable("location_kind", "operations");
                });

            modelBuilder.Entity("Shelter.Modules.Operations.Domain.LocationKindOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<bool>("HoldsAnimals")
                        .HasColumnType("boolean")
                        .HasColumnName("holds_animals")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Label", "Shelter.Modules.Operations.Domain.LocationKindOverride.Label#LocalizedText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_en")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_fr")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");
                        });

                    b.HasKey("Id")
                        .HasName("pk_location_kind_override");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_location_kind_override_tenant_id_code");

                    b.ToTable("location_kind_override", "operations");
                });

            modelBuilder.Entity("Shelter.Modules.People.Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<string>("PhoneDigits")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_digits")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("postal_code")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("preferred_language")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<string>("Province")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("province")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.PrimitiveCollection<string[]>("RoleTags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("role_tags")
                        .HasDefaultValueSql("'{}'")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("search_text")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<string>("SecondaryPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("secondary_phone")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<string>("SecondaryPhoneDigits")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("secondary_phone_digits")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.HasKey("Id")
                        .HasName("pk_person");

                    b.HasIndex("SearchText")
                        .HasDatabaseName("ix_person_search_text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .HasDatabaseName("ix_person_tenant_id_normalized_email");

                    b.HasIndex("TenantId", "PhoneDigits")
                        .HasDatabaseName("ix_person_tenant_id_phone_digits");

                    b.HasIndex("TenantId", "SecondaryPhoneDigits")
                        .HasDatabaseName("ix_person_tenant_id_secondary_phone_digits");

                    b.HasIndex("TenantId", "IsArchived", "DisplayName", "Id")
                        .HasDatabaseName("ix_person_tenant_id_is_archived_display_name_id");

                    b.ToTable("person", "people");

                    b.HasAnnotation("Shelter:AuditSubject", "Id");
                });

            modelBuilder.Entity("Shelter.Modules.Platform.Domain.InvitationToken", b =>
                {
                    b.Property<byte[]>("TokenHash")
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.HasKey("TokenHash")
                        .HasName("pk_invitation_token");

                    b.HasIndex("InvitationId")
                        .IsUnique()
                        .HasDatabaseName("ix_invitation_token_invitation_id");

                    b.ToTable("invitation_token", "platform");
                });

            modelBuilder.Entity("Shelter.Modules.Platform.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_organization");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_slug");

                    b.ToTable("organization", "platform");
                });

            modelBuilder.Entity("Shelter.Modules.Platform.Domain.SecurityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.HasKey("Id")
                        .HasName("pk_security_event");

                    b.HasIndex("UserId", "OccurredAt")
                        .HasDatabaseName("ix_security_event_user_id_occurred_at");

                    b.ToTable("security_event", "platform");
                });

            modelBuilder.Entity("Shelter.Modules.Platform.Domain.StaffInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("language")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.PrimitiveCollection<string[]>("RoleKeys")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("role_keys")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_staff_invitation");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_staff_invitation_tenant_id_created_at");

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_invitation_tenant_id_normalized_email")
                        .HasFilter("accepted_at IS NULL AND revoked_at IS NULL");

                    b.ToTable("staff_invitation", "platform");

                    b.HasAnnotation("Shelter:AuditSubject", "Id");
                });

            modelBuilder.Entity("Shelter.Modules.Platform.Domain.StaffMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.PrimitiveCollection<string[]>("RoleKeys")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("role_keys")
                        .HasDefaultValueSql("'{}'")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.HasKey("Id")
                        .HasName("pk_staff_membership");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_membership_tenant_id_user_id");

                    b.ToTable("staff_membership", "platform");
                });

            modelBuilder.Entity("Shelter.Modules.Platform.Domain.TenantSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.HasKey("Id")
                        .HasName("pk_tenant_setting");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_setting_tenant_id_key");

                    b.ToTable("tenant_setting", "platform");
                });

            modelBuilder.Entity("Shelter.Modules.Platform.Domain.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("concurrency_stamp")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<bool>("IsPlatformOperator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_platform_operator")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("preferred_language")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("security_stamp")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name")
                        .HasAnnotation("Shelter:FieldClassification", "Personal");

                    b.HasKey("Id")
                        .HasName("pk_user_account");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_user_account_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_user_account_normalized_user_name");

                    b.ToTable("user_account", "platform");

                    b.HasAnnotation("Shelter:AuditSubject", "Id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Shelter.Modules.Platform.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claim_user_account_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Shelter.Modules.Platform.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_login_user_account_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Shelter.Modules.Platform.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_token_user_account_user_id");
                });

            modelBuilder.Entity("Shelter.Modules.Animals.Domain.AnimalIdentifier", b =>
                {
                    b.HasOne("Shelter.Modules.Animals.Domain.Animal", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AnimalId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_animal_identifier_animal_tenant_id_animal_id");
                });

            modelBuilder.Entity("Shelter.Modules.Animals.Domain.TimelineEvent", b =>
                {
                    b.HasOne("Shelter.Modules.Animals.Domain.Animal", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AnimalId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_timeline_event_animal_tenant_id_animal_id");
                });

            modelBuilder.Entity("Shelter.Modules.Movements.Domain.Movement", b =>
                {
                    b.HasOne("Shelter.Modules.Movements.Domain.Movement", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "VoidsMovementId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movement_movement_tenant_id_voids_movement_id");
                });

            modelBuilder.Entity("Shelter.Modules.Operations.Domain.Location", b =>
                {
                    b.HasOne("Shelter.Modules.Operations.Domain.Location", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ParentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_location_location_tenant_id_parent_id");
                });
#pragma warning restore 612, 618
        }
    }
}
