// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shelter.BuildingBlocks.Persistence;

#nullable disable

namespace Shelter.Migrations.Migrations
{
    [DbContext(typeof(ShelterDbContext))]
    partial class ShelterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shelter.BuildingBlocks.Auditing.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_type");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.HasKey("Id")
                        .HasName("pk_audit_event");

                    b.HasIndex("TenantId", "SubjectId")
                        .HasDatabaseName("ix_audit_event_tenant_id_subject_id");

                    b.HasIndex("TenantId", "EntityType", "EntityId", "TimestampUtc")
                        .HasDatabaseName("ix_audit_event_tenant_id_entity_type_entity_id_timestamp_utc");

                    b.ToTable("audit_event", "audit");
                });

            modelBuilder.Entity("Shelter.BuildingBlocks.Auditing.PersonDataKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ShreddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shredded_at");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<byte[]>("WrappedKey")
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_key");

                    b.HasKey("Id")
                        .HasName("pk_person_data_key");

                    b.HasIndex("TenantId", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_person_data_key_tenant_id_subject_id");

                    b.ToTable("person_data_key", "audit");
                });

            modelBuilder.Entity("Shelter.Modules.Animals.Domain.Species", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Label", "Shelter.Modules.Animals.Domain.Species.Label#LocalizedText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_en")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_fr")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");
                        });

                    b.HasKey("Code")
                        .HasName("pk_species");

                    b.ToTable("species", "animals");
                });

            modelBuilder.Entity("Shelter.Modules.Animals.Domain.SpeciesOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Label", "Shelter.Modules.Animals.Domain.SpeciesOverride.Label#LocalizedText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_en")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_fr")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");
                        });

                    b.HasKey("Id")
                        .HasName("pk_species_override");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_species_override_tenant_id_code");

                    b.ToTable("species_override", "animals");
                });

            modelBuilder.Entity("Shelter.Modules.Movements.Domain.IntakeReason", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Label", "Shelter.Modules.Movements.Domain.IntakeReason.Label#LocalizedText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_en")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_fr")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");
                        });

                    b.HasKey("Code")
                        .HasName("pk_intake_reason");

                    b.ToTable("intake_reason", "movements");
                });

            modelBuilder.Entity("Shelter.Modules.Movements.Domain.IntakeReasonOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Label", "Shelter.Modules.Movements.Domain.IntakeReasonOverride.Label#LocalizedText", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_en")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                            b1.Property<string>("Fr")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label_fr")
                                .HasAnnotation("Shelter:FieldClassification", "NonPersonal");
                        });

                    b.HasKey("Id")
                        .HasName("pk_intake_reason_override");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_intake_reason_override_tenant_id_code");

                    b.ToTable("intake_reason_override", "movements");
                });

            modelBuilder.Entity("Shelter.Modules.Platform.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_organization");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_slug");

                    b.ToTable("organization", "platform");
                });

            modelBuilder.Entity("Shelter.Modules.Platform.Domain.TenantSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value")
                        .HasAnnotation("Shelter:FieldClassification", "NonPersonal");

                    b.HasKey("Id")
                        .HasName("pk_tenant_setting");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_setting_tenant_id_key");

                    b.ToTable("tenant_setting", "platform");
                });
#pragma warning restore 612, 618
        }
    }
}
